### ISSUE TITLE
prepare collecting biometry data from dcf

### ISSUE THREAD

**Issue by LBeaulaton** [ices-eg/wg_WGEEL#104]

**Comment by cedricbriandgithub** [comment]
Currently the database stores data for series in t_biometry_bio
This table collects data either from series of recruitment or yellow eel abundance ( or elsewhere
![image](https://user-images.githubusercontent.com/26055877/81852619-9b66f580-955b-11ea-9721-ea3e30a406ee.png)
The important part not appearing in this schema is the inheritance. 
T_biometrieseries_bis inherits from t_biometry_bio which means that this table contains all columns from t_biometry_bio.


```{sql}
-- Drop table

-- DROP TABLE datawg.t_biometry_series_bis;

CREATE TABLE datawg.t_biometry_series_bis (
	bis_g_in_gy numeric NULL, -- proportion (in %) of glass eel [100 for only glass eel ; 0 for only yellow eel ; the proportion if mix of glass and yellow eel]
	bis_ser_id int4 NULL,
	CONSTRAINT c_fk_ser_id FOREIGN KEY (bis_ser_id) REFERENCES datawg.t_series_ser(ser_id) ON UPDATE CASCADE
)
INHERITS (datawg.t_biometry_bio);

-- Column comments

COMMENT ON COLUMN datawg.t_biometry_series_bis.bis_g_in_gy IS 'proportion (in %) of glass eel [100 for only glass eel ; 0 for only yellow eel ; the proportion if mix of glass and yellow eel]';

-- Permissions

ALTER TABLE datawg.t_biometry_series_bis OWNER TO postgres;
GRANT ALL ON TABLE datawg.t_biometry_series_bis TO postgres;
GRANT ALL ON TABLE datawg.t_biometry_series_bis TO wgeel;
```

**Comment by cedricbriandgithub** [comment]
The biometries need to be added to the datacall file

**Comment by cedricbriandgithub** [comment]
Probably just add another table

something like

CREATE TABLE datawg.t_biometry_indiv_bii (
  bii_id serial PRIMARY KEY,
  bii_cou_code varchar(2),
  bii_emu_nameshort varchar(20),
  bii_area_division varchar(254),
  bii_hty_code varchar(2),
  bii_latitude_4326 numeric,
  bii_longitude_4326 numeric,
  --bii_lfs_code varchar(2), -- this might be a problem FOR individual DATA (maybe correct later)
  bii_date date ,
  bii_lengthmm numeric,
  bii_weightg numeric,
  bii_age numeric,
  bii_eye_diam_horizontal  numeric, --in mm
  bii_eye_diam_vertical numeric, --in mm
  bii_pectoral_fin_length NUMERIC, --in mm
  bii_comment TEXT,
  bii_last_update date,
  --bii_qal_id int4, -- Do we want that AT ALL ?
  bii_dts_datasource varchar(100),
  bii_geom geometry(point, 4326),
  CONSTRAINT c_fk_bii_dts_datasource FOREIGN KEY (bii_dts_datasource) REFERENCES "ref".tr_datasource_dts(dts_datasource),
  --CONSTRAINT c_fk_bii_lfs_code FOREIGN KEY (bio_lfs_code) REFERENCES "ref".tr_lifestage_lfs(lfs_code) ON UPDATE CASCADE,
  --CONSTRAINT c_fk_bii_qal_id FOREIGN KEY (bii_qal_id) REFERENCES "ref".tr_quality_qal(qal_id)
  CONSTRAINT c_fk_bii_area_code FOREIGN KEY (bii_area_division) REFERENCES "ref".tr_faoareas(f_division) ON UPDATE CASCADE,
  CONSTRAINT c_fk_bii_cou_code FOREIGN KEY (bii_cou_code) REFERENCES "ref".tr_country_cou(cou_code),
  CONSTRAINT c_fk_bii_emu FOREIGN KEY (bii_emu_nameshort,bii_cou_code) REFERENCES "ref".tr_emu_emu(emu_nameshort,emu_cou_code),
  CONSTRAINT c_fk_bii_hty_code FOREIGN KEY (bii_hty_code) REFERENCES "ref".tr_habitattype_hty(hty_code) ON UPDATE CASCADE,
  CONSTRAINT c_nn_bii_date CHECK (bii_date) NOT NULL,
  CONSTRAINT c_ck_bii_lengthmm CHECK (bii_lengthmm>0 OR bii_lengthmm IS NULL),
  CONSTRAINT c_ck_bii_lengthmm CHECK (bii_weightg>0 OR bii_weightg IS NULL),
  CONSTRAINT c_ck_bii_bii_age CHECK (bii_age>0 OR bii_age IS NULL),
  CONSTRAINT c_ck_bii_eye_diam_horizontal CHECK (bii_eye_diam_horizontal>0 OR bii_eye_diam_horizontal IS NULL),
  CONSTRAINT c_ck_bii_eye_diam_vertical CHECK (bii_eye_diam_vertical>0 OR bii_eye_diam_vertical IS NULL),
  CONSTRAINT c_ck_bii_pectoral_fin_length CHECK (bii_pectoral_fin_length>0 OR bii_pectoral_fin_length IS NULL)
)
;

**Comment by cedricbriandgithub** [comment]
![daig2](https://user-images.githubusercontent.com/26055877/167600713-94707330-98fa-42f4-9723-52e43798461e.png)
The code is [here :] https://github.com/ices-eg/wg_WGEEL/blob/master/SQL/database_edition_2022.sql)

**Comment by cedricbriandgithub** [comment]
TODO
* [ ] integrate template data from excel table 
* [ ] test triggers for last update, biometry, quality, group and individual, date with different year.
