### ISSUE TITLE
habitat area set to 0

### ISSUE THREAD

**Issue by elfunesto** [ices-eg/wg_WGEEL#121]
in datawg.t_eelstock_eel, some habitat surface (eel_typ_id=16) are set to 0 while habitats indeed exist and there are landings in them. See for example FR_Adou hty='T'
zeros values
`select * from datawg.t_eelstock_eel where eel_typ_id=16 and eel_value=0`

**Comment by cedricbriandgithub** [comment]
we didn't ask for habitat this year datacall, do we close that comment ?

**Comment by cedricbriandgithub** [comment]
habitat is unreliable, hasn't been asked in the new data call, I suggest to close this one
