### ISSUE TITLE
Units in visualisation

### ISSUE THREAD

**Issue by jdpo** [ices-eg/wg_WGEEL#122]
The units (I checked it for releases) are not shown if you display/export a table

**Comment by elfunesto** [comment]
How would you like units to be displayed? For landings, it is specified in the text above the table so we can do the same for other tables. However, in that case, units would not be displayed when exported in excel. Another solution is to put the units in the column names (for example FR_ton) to keep the information when exported to excel but then, it makes very long and redundant column names.

**Comment by jdpo** [comment]
I really have not given it much thought to be honest. It should be visible in the excel too I guess, but the column names indeed seem a bit over the top.  
Once exported, the excel file has a header saying "ICES data visualisation", maybe it can be shown here. Or even better, another header below this one can be created potentially showing more information (e.g. staghes and habitat, guess those are also not in the excel file).

It is not a high priority though since it can easily be done e.g. in the filename. Just recognized it and wanted to create reminder on the GIT. I didn't even expect it to be read by anyone, so I am quite amazed that it is already been taken care of:)

**Comment by elfunesto** [comment]
It is an easy one, so typically the kind of issues you can solve while making other things ;-)

**Comment by elfunesto** [comment]
Hi again, commit 7950233 solved the issue: it adds a table caption with units and it is exported in the excel file. Can you check this is ok for you @jdpo ?

**Comment by jdpo** [comment]
Hi, if I export the releases to excel from the shiny visualisation I can't find a caption...

**Comment by elfunesto** [comment]
this one? 
![Capture du 2020-05-27 15-58-04](https://user-images.githubusercontent.com/43066644/83029610-21db0700-a033-11ea-8a8f-8abfea58a578.png)
![Capture du 2020-05-27 16-00-22](https://user-images.githubusercontent.com/43066644/83029654-31f2e680-a033-11ea-89c2-b4815b535f78.png)

**Comment by elfunesto** [comment]
I have pushed the new version in github but it is not yet on Cedric's server, so you have to try it locally on your machine after pulling

**Comment by cedricbriandgithub** [comment]
I've loaded the new files

**Comment by jdpo** [comment]
thx!
