### ISSUE TITLE
correction for Estonia

### ISSUE THREAD

**Issue by elfunesto** [ices-eg/wg_WGEEL#127]
update datawg.t_eelstock_eel set eel_area_division='27.3.d' where eel_emu_nameshort='EE_West' and eel_emu_nameshort is null;

**Comment by cedricbriandgithub** [comment]
update datawg.t_eelstock_eel set eel_area_division='27.3.d' 
where eel_emu_nameshort='EE_West' 
and eel_area_division is NULL
and eel_hty_code='C'
AND eel_typ_id IN (4,6);
