### ISSUE TITLE
notes for datacall 2021 - feedbacks 2020

### ISSUE THREAD

**Issue by elfunesto** [ices-eg/wg_WGEEL#129]
- comments from Russel: In annex 1, recruitment table, specify that bio_g_in_gy should be in the same unit as das_value
- question from Clarisse: how to remove data from the db, for example a recruitment for a specific year? in new value, put the year and put NC
- Pitt: for the last year; prefill data with the same details of aggregation than previous year (for example YS instead of splitting in Y and S)
- Cedric : we will need an updated_biometry sheet in annex 1, 2, 3 & develop shiny for those

- Cedric : remove bis_ser_id from new_biometry

- Jason : annex 3, there is no instruction for sex ratio in column bio-sex-ratio. 
It should be calculated as the percentage of female.
 "(number of females/(number of males+number of females))*100" (ie % female)
- Clarisse Annex 1,2,3 value for year restricted to an integer.

- Hilaire: careful with the year restriction in Release (currently max 2017)
- Hakan: clarify that aquaculture is only for human consumption
- Alan: specify how to deal with multiple data provider in the metadata sheet

- Hilaire: for time series, prefilled new_data should not propose year before the first year of data (e.g. In Belgium, we should not propose a value for VeAmGY  year 2010  while the monitoring started in 2017)

- The message in annex 1 2 3 for series  area division is wrong

> Fao   code of sea region (division level) see    tr_fao_area (column division)(https://github.com/ices-eg/WGEEL/wiki).   These codes are for use only in the case of Coastal and Marine Open waters –   otherwise you can leave it blank. ICES statistical rectangles   (http://gis.ices.dk/sf/index.html?widget=StatRec) and FAO areas map   (http://www.fao.org/fishery/area/search/en)

We need area division to know to which sea the river flows.

**Comment by cedricbriandgithub** [comment]
Comments about data integration
