### ISSUE TITLE
Change R version on linux server

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#138]
Current version is 3.4.4, test all apps before changing. No time to do this now

**Comment by cedricbriandgithub** [comment]
saving Rdata for the server require using version =2
save(participants,list_country,typ_id,the_years,t_eelstock_eel_fields, file=str_c(getwd(),"/common/data/init_data.Rdata"), version=2)

Otherwise error "problem with magick number"

**Comment by elfunesto** [comment]
When done, we can try to change some leaflet maps to mapview maps (especially in data integration) to improve display performance
