### ISSUE TITLE
develop tutorial for data group 

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#141]

**Comment by cedricbriandgithub** [comment]
I'm just doing this to past screenshot and use their url, here I can drag & drop
![start_screen](https://user-images.githubusercontent.com/26055877/91455981-0a562900-e883-11ea-80cc-6dc1db4e1974.png)

**Comment by elfunesto** [comment]
![Capture d’écran du 2020-08-28 15-30-01](https://user-images.githubusercontent.com/43066644/91566144-831cba00-e943-11ea-9814-dbbda212c5f0.png)

**Comment by cedricbriandgithub** [comment]
done
