### ISSUE TITLE
Add stuff to series and biometric data

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#144]
following comment from Russell who is right 👍

**Comment by cedricbriandgithub** [comment]
# Biometry level

The biometric data should include number


# Series level

At the series level, we should have information about
  * distance to the sea (average distance for some sites, or leave empty in places where series cover a whole basin (electrofishing sites)
* description of the method used, perhaps drawn from a reference table of possible survey methods. Elsa said that method changed over year, do we want to go to that level of complexity or store it in the ser_description where an extensive description of the method should lie ? I think the second is preferable.
*

**Comment by LBeaulaton** [comment]
--> means inheritage link
* t_biometry_other_bit: 180 data used in 2019 (last update for all is 08/09/2019) ; this is not related to t_series_ser while some of them may be related (create at a time we do not have this in the database)
* t_biometry_series_bis: is related to t_series_ser, but not directly to dataseries, even though it can be related through t_series_ser

**Comment by cedricbriandgithub** [comment]
# lot of missing sampling types

Copied from another two  issues opened by Hilaire: 

OK, but now the sampling type were only designed for glass eel series, so we have to extend the table for yellow and silver series !

the analysis of biometry data would require to have more precise sampling type. Electrofishing?

**Comment by elfunesto** [comment]
I agree with Laurent that, if gear changed, the time series is not a conistent time series of abundance, so should be splitted

**Comment by elfunesto** [comment]
Perhaps we should have something about restocking which is thought to influence many of this time series, but do not know really the level of precision we should use.

**Comment by cedricbriandgithub** [comment]
Done added number to datawg.t_biometry_bio and ser_sam_gear  ser_distanceseakm ser_methoddescription to series table
-- | -- | --
