### ISSUE TITLE
Add a line of text explaining the table (summary of duplicated,... updated values) and for the detect missing

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#147]

**Comment by elfunesto** [comment]
I have started to reorganise a litlle bit the interface in integration of t_eel_stock, each table has now a heading. we can latter add a small paragraph of description
All data that need to be downloaded in step 1 (new_data, updated_data, duplicates_data) appear first, then the two tables that summarize the situation appear below.
