### ISSUE TITLE
2018 data call integration

### ISSUE THREAD

**Issue by LBeaulaton** [ices-eg/wg_WGEEL#15]
* send to countries 2017 data
* replace constraint on quality by a trigger
* create a temporary table and copy in it previous data and the new one
* 3 possibilities then
   - unique data --> keep for later insertion in the database
   - same data in two exemplar --> delete the new one
   - different data --> send a ranked table to CR leader. They should choose the one to keep through quality

**Comment by cedricbriandgithub** [comment]
* The datacall did not contain previous data, so there is no way to check against existing data... we have to find a programmatically way to handle this.

```sql

  CONSTRAINT c_fk_qal_id FOREIGN KEY (das_qal_id)
      REFERENCES ref.tr_quality_qal (qal_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
```

**Comment by cedricbriandgithub** [comment]
With a trigger, or an R code, modify the comment to include data from `eel_datasource`  changed from
`old_eelvalue` to `new_eelvalue`

**Comment by cedricbriandgithub** [comment]
This has been done with an R code, the details are more complex than this, as we have to keep all data from the database and the datacall according to user choice. This is mostly done in 
https://github.com/ices-eg/wg_WGEEL/blob/master/R/shiny_data_integration/shiny/database_tools.R
