### ISSUE TITLE
Recruitment series

### ISSUE THREAD

**Issue by LBeaulaton** [ices-eg/wg_WGEEL#16]
Polish recruitment graph, remove the black dots (arithmetic average)
Add comments on yellow eel trend graph in the rnw
Treat more properly the zero data (at least give series/year)

**Comment by cedricbriandgithub** [comment]
for recruitment graph, calculate geometric means, pb is that geommean kind of return a list, so technical pb to be solved. We don't have to remove just transform to geometric

**Comment by cedricbriandgithub** [comment]
Willem says : don't put an incomplete information (eg geometric means) which will be biaised by missing data, just show the raw data, no mean, no nothing. We go on for next year and then drop it

**Comment by cedricbriandgithub** [comment]
https://github.com/ices-eg/WGEEL/commit/c4191b17819fdb1406d5d213100f1d691d8114f8
this is not very convincing
