### ISSUE TITLE
develop a database edition tools for series and biometry

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#163]
Importing excel file is fine for integration but really heavy if we have to do database edition. Currenly the edition tool only works for t_eelstock_eel table. We would need one for series. And one for biometries... to integrate last time change.
Note I have one edition tool in libreoffice but then I have to maintain it also and it's sufering from the lack of operational maintenance.

**Comment by elfunesto** [comment]
Done, there is a generic datatable edition in shiny data integration that also allows to edit coordinates on a map
