### ISSUE TITLE
national report

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#166]
Alan :
> Glass eel landings table - there is a 'total' column third from the right that is not required.
>> no this is national level when you report at national level

>Landings recreational (all life stages) - Scotland in 2020 should be the same as everywhere else - a 0 meaning no landings, not the '.' that appears in the tables.
>> I think there is a NR in the database for this year for Scotland.

> Recruitment series figures - left box says False, right box says True - needs an explanation
![image](https://user-images.githubusercontent.com/26055877/93687971-96462400-fac2-11ea-8987-f267229b816a.png)
>> there is a "panel indicate if selected now"

>Maps of series - would be better to show the whole nation rather than crop bits 
>> Was centered on existing series, now centered on country, done !

![image](https://user-images.githubusercontent.com/26055877/93687991-c097e180-fac2-11ea-89b1-36d6dff65656.png)

**Comment by elfunesto** [comment]
treated by @cedricbriandgithub
