### ISSUE TITLE
problems with data call / report and other 2020

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#167]

**Comment by cedricbriandgithub** [comment]
# sweden

* Seems some data are missing compared to what Josefin has sent in.

* I also wonder about the unit for releases in number, the graph says millions, but that we as an example released 60 million eels in 1977 and that as yellows in inland waters seems totally weird. The corresponding weight in 1977 was 47,6 ton and that doesn’t fit as the yellows at that time was about 80 grams each.
> this is related to issue https://github.com/ices-eg/wg_WGEEL/issues/109

*	When SE doesn’t distinguish between yellows and silvers as most anyhow are silver eels, is then/should then the catch of yellow be a 0 or an empty cell? This refers to Table 1 where both 0 and dots occur.
*	If silver eels aren’t caught at our West coast (or the few there must have been weren’t distinguished from the bulk of yellows), is then the catch 0 or a dot? Refers to Table 2.
*	The same table is missing data for 2019 that we must have reported. 
*	Table 3 and 4. Sweden has decided there are no recreational catches as only professional eel fisheries are allowed (simple solution by the government!). Is then the catch consistently a 0 or a dot?
*	The release issues again. When you state e.g. 60 as a number for year 1977 in both Table 5 and the corresponding graph, is that really in millions?
*	If so, how could we come to that extremely high figure? In that very case it corresponds to ca 47,6 ton of yellows in inland waters. They were about 11 in a kg, so a more reasonable figure would be ca 524 000 eels.
*	Also in these tables there is a mix of 0 and dots.
*	As we think we knows what was released every year, I assume a 0 would be the right choice to be used instead of dots.
*	There were nothing on Aquaculture, but I am sure you got those data.
*	Figure 14, aren’t two dots missing (the YFS’s)?

**Comment by cedricbriandgithub** [comment]
# Germany

Lasse has some troubles, he will send a list

**Comment by cedricbriandgithub** [comment]
# Spain

for yellow standing stock we have two series OriY aand AlCY. However, there is only a figure for OriY and in the Figure description it says recruitment Y, while it is standing stock data.

~~personal note Also the trend is linear, and shoud be a gam => fixed~~

**Comment by cedricbriandgithub** [comment]
# Finland

There are missing recreational landings for 2016 2018 for some reason they were not on the sharepoint

**Comment by cedricbriandgithub** [comment]
# UK

Several comments on Scotland's data in the automated country report export on the sharepoint......

For a number of your tables - not just thew one Alan spotted - the 2020 value for Scotland is given as "." In all cases it should be "0"

In general it is hard for me to tell some of the colours apart on the figures, so it's difficult to be sure the data look right.

Map for yellow eel standing stock and silver eel escapement sites doesn't really work for Scotland as both yellow and silver are reported for all three sites - but you can't tell that from the map - looks like there's only silver eel data.

Finally and most importantly, I sent you the 2020 data for the yellow eel recruitment series at the Girnock (GirnY) on the 15th Sept - it looks like either you didn't receive it or you haven't managed to include it for some other reason. Do you need me to send it again?

**Comment by cedricbriandgithub** [comment]
# LV


# yellow and silver series the format was wrong... Janis only sent the update today and I had forgeten that I ever asked :-o Need to be integrated. New file CORRECTED in LV on the sharepoint
00:01
--
01:07
01:01
00:01
01:05

**Comment by cedricbriandgithub** [comment]
# PL  

In the autamated CR for landings yellow eels and silver for 2019 some strage numbers appears. Shoul be 0 – we report only for combined YS stage
Also aquaculture data is missing

**Comment by sozdilek** [comment]
> # LV
> * yellow and silver series the format was wrong... Janis only sent the update today and I had forgeten that I ever asked :-o Need to be integrated. New file CORRECTED in LV on the sharepoint
>   00:01
>   --
>   01:07
>   01:01
>   00:01
>   01:05

>yellow series: 2 values updated in the db and 8 new values inserted in the database

**Comment by ClarisseBoulenger** [comment]
### IE

- I think all the data are there and correct, but there are some duplications between tables 1, 2 and 3 – are these ok?

- Some of the numbers in the releases are rounded up, where others are given to 2 decimal places – why the inconsistency.

- I have the end of year recruitment data for all Irish traps now, I guess I don’t include it now at this late stage, just update in 2021?

**Comment by ClarisseBoulenger** [comment]
### LT
they give two times the same information. One time in the updated_data sheet where they put the value for YS life stage and a second time in the new data where for the same year they put value for Y and S life stage and if you look closely YS (updated data)=Y (new_data)+S (new data). That's why Lithuanian landing data looked like doubled since 2000
> **Correction need to be done in with Arvydas**
