### ISSUE TITLE
Preparing 2021 data call

### ISSUE THREAD

**Issue by LBeaulaton** [ices-eg/wg_WGEEL#168]
# 2021 data call
new data to be asked for:
* biomass : B0, Bbest, B current
* mortality: A, H, F
* habitat

# problems we have had with the 2018 data call on these data
* reporting by ICES division (NO only)
* life stage being different between mortality or between mortality and biomass
![image](https://user-images.githubusercontent.com/26081069/93890321-84df6080-fcea-11ea-8d2b-dcacd6bdc9e9.png)
![image](https://user-images.githubusercontent.com/26081069/93895344-04bbf980-fcf0-11ea-8a85-286c2eca4d59.png)
* Date for B0 to be homogenized + some countries give an evolving B0
![image](https://user-images.githubusercontent.com/26081069/93894302-dd186180-fcee-11ea-8873-ef11674c99f8.png)
* habitat surface being provided at a different aggregation level (habitat, life stage) than biomass
![image](https://user-images.githubusercontent.com/26081069/93894683-48623380-fcef-11ea-9f16-d952ea4bd460.png)

# proposed controls / instructions
1. do not report by ICES division
1. life stage for Biomass should be 'S'
1. mortality be provided for 'AL' life stage ==> up to the data providers to make the sum. The risk is to loose data on mortality at a given life stage because data provider do not have mortality for all life stages
1. year for B0 being arbitrarily fixed to 1800 for 'fixed' B0 or being provided for every year when evolving (but what is the reason for a evolving B0?)
1. life stage for habitat should always be 'AL' (however this should be handled when querying with biomass)

# National reports

Method. Habitat. Projection forward of current management

**Comment by LBeaulaton** [comment]
SG1 discussion:

* Restocking should be a negative mortality? ==> LB make a text
* data from database flag as dc2020 to avoid any problem
* provide lifespan duration (use in the calculation of B&A) in the country report (along with the description of methods, ...)
* Bbest: what projection?
3. 'AL' mandatory, and if available other lfs can be given

**Comment by cedricbriandgithub** [comment]
ALAN's comments
•	We should make sure the Stock Annex has habitat definitions that we all agree to use – that is, what makes the boundary between the habitat types. 

•	Evolving B0 – maybe a small issue but remind all that any country that changes their data or method, applies that backwards to their time series of Bs and As. This might address a small part of the evolving B0 issue.
