### ISSUE TITLE
trigger not fired for eel_last_update when correcting on the database 

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#169]
CREATE TRIGGER update_eel_time BEFORE
INSERT
    OR
UPDATE
    ON
    datawg.t_eelstock_eel FOR EACH ROW EXECUTE PROCEDURE datawg.update_eel_last_update();

CREATE OR REPLACE FUNCTION datawg.update_eel_last_update()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.eel_datelastupdate = now()::date;
    RETURN NEW;	
END;
$function$
;

**Comment by elfunesto** [comment]
i think it should be an "after" trigger rather than a "before" trigger

**Comment by elfunesto** [comment]
made some tests with both insert and update and it is working
