### ISSUE TITLE
add hexadecimal color code in the db, table ref.tr_country_cou

### ISSUE THREAD

**Issue by elfunesto** [ices-eg/wg_WGEEL#170]
This is currently defined in R script through values=c(RColorBrewer::brewer.pal(12,"Set3"),
		RColorBrewer::brewer.pal(12, "Paired"), 
		RColorBrewer::brewer.pal(8,"Accent"),
		RColorBrewer::brewer.pal(8, "Dark2"))
color_countries = setNames(values,country_ref$cou_code)

We can also have a look at [hues](https://cran.r-project.org/web/packages/hues/hues.pdf) or [colorspace](https://cran.r-project.org/web/packages/colorspace/vignettes/colorspace.html)

**Comment by mariazti** [comment]
Reading tutorials from [Iwanthue](https://medialab.github.io/iwanthue/examples/), I have selected the colour scale they propose for large palettes, and this is the result: `iwanthue(40, 0, 360, 0, 85, 30, 95, plot=TRUE, random = TRUE)`
![image](https://user-images.githubusercontent.com/40487850/168318260-8a843c96-a16b-44eb-a2fe-b674be8914fc.png)

I have the script ready to add the colour column to the country and EMU tables, I just need to know if you want to keep the colour (@ClarisseBoulenger proposed not to change it), or you prefer a constant scale (@cedricbriandgithub proposed to homogenise the colours).

**Comment by ClarisseBoulenger** [comment]
Are the colors of the new palette visible to the coloblindness? If so, it's not a problem to change them. If not, it's why we had a hard time choosing colors from different palettes to meet the demands of some of the working group. @cedricbriandgithub @mariazti
