### ISSUE TITLE
historical data for release do not allow to convert from weight to number 

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#177]
![image](https://user-images.githubusercontent.com/26055877/94707529-d1a6e500-0343-11eb-8a1b-d01e6601f1a8.png)
![image](https://user-images.githubusercontent.com/26055877/94707568-df5c6a80-0343-11eb-9074-0d3c5554fe39.png)
It's just that checking graphs, much less countries have reported in weight than in number though this should have been the standard with new data call format. Means that some historical data are missing weight and we cannot convert age ...
Do we want to do that, will we one day open the pandora box ?

**Comment by elfunesto** [comment]
waiting if needed one day
