### ISSUE TITLE
WKEELDATA3 - Things to check for in next data call

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#179]
# WKEELDATA3 

## ALL

* Problems with edition / cell restrictions in the excel
* metadata / data providers => add a way to deal with several of them ... We don't really bancarize them anyways.
* Preffilled data, users should not report emply lines 
* #126

## SERIES

* Don’t worry is no need for units at data level if units have been provided at the series level
* Area divisions should be provided for series (unlike what we stated in the sheets).
* Sex ratio (instructions were missing)
* We should provide numbers sampled for biometry data
  * test update biometry shiny #162
  *  missing things in biometry #144 => update database and then update shiny....

## BIOMASS MORTALITY

Instructions
* Data should by reported by EMU and habitat (Freshwater ‘F’, Transitional water ‘T’, Coastal water ‘C’, or all habitat ‘AL’) and should never be split by ICES division.
*  Life stage for biomass should only be silver eel (‘S’).
* Mortalities data have to be provided as total lifespan mortalities (thus lifestage ‘AL’). If mortalities data per lifestage are available, they can also be provided as complementary information.
* Mortalities should be computed in number, not biomass
* metadata should integrate instructions about cohort wise or year wise (use yearwise when possible) and the user must specify what type of calculation has been done
* For pristine biomass (B0) the year should be arbitrarily fixed to 0 and there is no reason that B0 changes over time since it refers to a pristine situation.
* The Lifestage used for habitat surface should only be all habitat (‘AL’) since there is no reason for variable available habitats among stages.
* Restocking should be included only in Bcurrent, make paragraph to explain
* When ΣA is calculated as the ratio between Bcurrent and Bbest, biomasses should be ex-pressed in numbers in that calculation and both biomasses should come from the same recruitment year (i.e. in the example above both from 2011 or both from 2020). If restock-ing is included in Bcurrent, the ratio between Bcurrent and Bbest no longer reflects the total mortality ΣA.
*  #121

## LANDINGS AND AQUACULTURE

#176 check for germany, provide specific instructions
#136 Sweden Ask to consistently report all aquaculture
#109 Sweden Release for sweden give specific instructions

## Things to be done:
-  ~copy latest datacall files to sharepoint (Cédric)~
- ~check problems with current templates (Clarisse)~
- generation of  templates (common to all) then test scripts to generate files for all countries
  * ~Biomass (Hilaire)~
  * ~Mortality (Laurent)~
  * Time series (Cédric)
  * other usual (landings, aquaculture) Sukran Burcu
 - Database (Cédric) 
   *  ~Change series table (database)~
   * ~modify the templates~
   *  ~Discard old data (biomass and mortality) as qal_id=20~
- ~edit cover letter and instructions sheets~

- creation of a script to integrate stock indicators
-- ~check validity of the file (Clarisse and María)~
-- ~display new data, updated data, duplicates (Clarisse and María)~
-- ~integrate in the db~
- develop aggregation routines (summing up stock indicators at the country level)
- ~Move shiny server to 4.0.5 (currently development in local)~
- Correct comment for sum_h_release set as DEPRECATED

**Comment by elfunesto** [comment]
### Things to be done:

- generation of all templates for all countries
- creation of a script to generate templates for stock indicators
- creation of a script to integrate stock indicators
-- check validity of the file
-- display new data, updated data, duplicates
-- integrate in the db
