### ISSUE TITLE
add column in database to indicate public record

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#18]
Following an exchange with Neil,  as with the VME and Biodiversity type data, we will add a field to the t_eelstock_eel table to indicate if it is a public/restricted record.

The data from bird reporting guidance http://ices.dk/marine-data/Documents/biodiversity/Birds_Reporting_Format_Guidance.pdf  give a hint on what terms are used

----

Data Access
OSPAR is committed to making as much information as possible publicly available, consistent with achieving
other similarly important goals of public policy. The framework for this is set out in Article 9 of the OSPAR
Convention and Annex 3 of the OSPAR Rules of Procedure (2013-2).
Contracting Parties should contact Chris Moulton (Chris.Moulton@ospar.org) if they have any queries over
what data to include in the submissions.
Data access can be specified by the submitters directly in the submission form as:
**Public** Data are sourced outside the terms of the OSPAR data policy and are publically accessible
**Restricted** Data, in their reported form, are not to be made publically accessible. All aggregated data
products are, by default, publically available, including those derived from restricted data
**OSPAR** Data are collected under the terms of the OSPAR data policy, and will be made available
in line with the terms. Ref. Annex 3 http://www.ospar.org/site/assets/files/1215/13-
02e_rules_of_procedure.doc

---

So build a restricted character varying field with check constraint

**Comment by neil-ices-dk** [comment]
@cedricbriandgithub you can also make use of the controlled vocab we have in http://vocabulary.ices.dk called 'Data_access', downloaded the current values and attached in case it's of use here 
[RECO_Export_17-24-2018.xlsx](https://github.com/ices-eg/wg_WGEEL/files/1638148/RECO_Export_17-24-2018.xlsx)

**Comment by cedricbriandgithub** [comment]
```sql
CREATE TABLE ref.tr_dataaccess_dta(
dta_code character varying(20) primary key,
dta_description text);
INSERT INTO ref.tr_dataaccess_dta(dta_code,dta_description) values ('Public','Public access according to ICES Data Policy');
INSERT INTO ref.tr_dataaccess_dta(dta_code,dta_description) values ('Restricted','Restricted access (wgeel find a definition)');
-- inserting a new column and refering to the new referential table
ALTER TABLE datawg.t_eelstock_eel add column eel_dta_code character varying(20);
ALTER TABLE datawg.t_eelstock_eel add constraint c_fk_eel_dta_code FOREIGN KEY (eel_dta_code)
      REFERENCES ref.tr_dataaccess_dta (dta_code) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE NO ACTION;

```
The table sent by Niel has the following definition : 'Restricted data access to the delivered level of aggregation  not affecting the products', what are the restrictions envisionned for ICES wgeel data (especially those coming from the datacall).

**Comment by SabineAllou** [comment]
the reference table tr_dataaccess_dta is created with 'Public' or 'Restricted' and also the column eel_dta_code in the table t_eelstock_eel with the default value 'Public'. see [database_edition_2019](https://github.com/ices-eg/wg_WGEEL/blob/master/SQL/database_edition_2019.sql)
