### ISSUE TITLE
quick bug shiny 2021

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#182]

**Comment by jdpo** [comment]
* after uploading releases, check file for releases_DE produces the error "undefined columns selected"

**Comment by sozdilek** [comment]
In the Time series data integration of IR Annex 3 (silver eel), I think there is a problem in the heading of updated biometry. When I delete the first empty line, a problem is going on. 
1 | dataset <updated_biometry>,   column <bio_id>, missing values line 1 |  
1 | dataset <updated_biometry>,   column <bio_id>, missing values line 1 |  
2 | dataset <updated_biometry>,   column <bio_id>, missing values line 2 |  
1 | dataset <updated_biometry>,   column <bio_year>, missing values line 1 |  
1 | dataset <updated_biometry>,   column <ser_nameshort>, missing values line 1

**Comment by sozdilek** [comment]
In yellow eel series Annex 2: Error: object 'res' not found

**Comment by sozdilek** [comment]
> In yellow eel series Annex 2: Error: object 'res' not found

The error is the same both in NL and in IR data

**Comment by sozdilek** [comment]
Mortality rates: Error: argument "namedataset" is missing, with no default

**Comment by sozdilek** [comment]
> Mortality rates: Error: argument "namedataset" is missing, with no default
The problem is in IR data
The integration of the Mortality rates of NL is working.

**Comment by sozdilek** [comment]
Annex 7: The error: release 
dataset <new_data>, column <eel_area_division>, missing values line 1 
However, there is no column as "eel area division" in release data
