### ISSUE TITLE
pb Integration of the same line two times

### ISSUE THREAD

**Issue by ClarisseBoulenger** [ices-eg/wg_WGEEL#186]
We can integrate for the same year, hty, emu, lfs two lines: one line with a missing value and a NC and one with a value. Many of these in the database
````sql
select eel_typ_id,eel_year,eel_emu_nameshort, eel_lfs_code,eel_hty_code, count(*) 
from datawg.t_eelstock_eel where eel_qal_id in (0,1)
 group by eel_typ_id,eel_year,eel_emu_nameshort, eel_lfs_code,eel_hty_code
 having count(*) >1
```

**Comment by cedricbriandgithub** [comment]
````sql
-- 194 some of those correspond to coastal waters with area division 
-- two separate columns for area division
WITH cc AS (
select 
eel_typ_id,
eel_qal_id,
eel_year,
eel_emu_nameshort, 
eel_lfs_code,
eel_hty_code, 
eel_area_division,
eel_value, 
eel_missvaluequal, 
count(*) OVER (PARTITION BY eel_typ_id,eel_year,eel_emu_nameshort, eel_lfs_code,eel_hty_code,eel_area_division)  AS n
from datawg.t_eelstock_eel where eel_qal_id in (0,1))
SELECT * FROM cc WHERE n>1
```

**Comment by cedricbriandgithub** [comment]
qal data is never 0 when taken from calculations ...
In extract data we use qal_id 1, 2 and 4 ...

**Comment by cedricbriandgithub** [comment]
-- Same query but only using stages that are used
WITH cc AS (
select 
eel_typ_id,
eel_qal_id,
eel_year,
eel_emu_nameshort, 
eel_lfs_code,
eel_hty_code, 
eel_area_division,
eel_value, 
eel_missvaluequal, 
count(*) OVER (PARTITION BY eel_typ_id,eel_year,eel_emu_nameshort, eel_lfs_code,eel_hty_code,eel_area_division)  AS n
from datawg.t_eelstock_eel where eel_qal_id in (1,2,4))
SELECT * FROM cc WHERE n>1
