### ISSUE TITLE
DK_total

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#187]
In the database DK_total means in fact DK_marine waters, only coastal. The 50 % reduction was applied there from the start.
Change it to DK_marine so as to avoid confusion.

**Comment by elfunesto** [comment]
leave DK_total to handle sum of DK_mari and DK_inla

**Comment by elfunesto** [comment]
This creates DK_Mari. We will have to discuss with Michael whether former DK_total records can be associated with DK_Mari

begin;
insert into ref.tr_emu_emu (emu_nameshort,emu_name,emu_cou_code,emu_wholecountry) values('DK_Mari','Danish coastal and marine waters','DK',FALSE);
SELECT setval(pg_get_serial_sequence('ref.tr_emusplit_ems', 'gid'), COALESCE((SELECT MAX(gid) + 1 FROM ref.tr_emusplit_ems), 1), false);
insert into ref.tr_emusplit_ems (emu_nameshort,emu_name,emu_cou_code,emu_hyd_syst_s,emu_sea,emu_cty_id ,meu_dist_sargasso_km)  
	(select 'DK_Mari' emu_nameshort,'Danish coastal and marine waters' emu_name,e.emu_cou_code,e.emu_hyd_syst_s,e.emu_sea,e.emu_cty_id,e.meu_dist_sargasso_km  from ref.tr_emusplit_ems e where e.emu_nameshort ='DK_Inla')
	
	commit;
