### ISSUE TITLE
year to year change

### ISSUE THREAD

**Issue by LBeaulaton** [ices-eg/wg_WGEEL#19]
check that the new calculate series has no major differences with past series published (or explain difference). e.g. the 1997 value has major change between 2015-2016 and 2016-2017 (2017 value close from 2015 and former value). Why ?

**Comment by cedricbriandgithub** [comment]
This was documented during wgeel and there was a problem with calculations in 2015-2016, also many series reported a major change, see individuals comments to see what value was changed.
