### ISSUE TITLE
Minor formatting issue

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#190]
Automatic reports for country :

On the bar charts I find the colour-coding (it looks like viridis option D to me) hard to identify the EMUs from. This problem is alleviated where the legend only includes EMUs that actually contribute any data (e.g. as in Silver landings). However in the Releases, even though it contributes nothing, GB_Scot appears in the legend .... and if I didn't already know that it contributes nothing, I'd think it contributed something but wouldn't be able to identify what. So, I'm suggesting that all those EMUs that contribute nothing (whether NAs or Zeros) should be removed from the legend. Of course, you provide the data alongside the graph, so this is only a minor presentation issue. But who knows where these graphs may end up?

**Comment by elfunesto** [comment]
automatic_graphs_tables
