### ISSUE TITLE
the trigger to update the coordinates does not work

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#193]
CREATE TRIGGER update_coordinates AFTER
UPDATE
    OF geom ON
    datawg.t_series_ser FOR EACH ROW EXECUTE FUNCTION datawg.update_coordinates()

fires

column geom does not exist ????

**Comment by elfunesto** [comment]
how did you received this error, i.e. how did you try updating the geom?

**Comment by cedricbriandgithub** [comment]
UPDATE datawg.t_series_ser SET geom =
ST_transform(ST_SETSRID(ST_MakePoint(417768.557,6779552.138 ),3067),4326)
WHERE ser_nameshort='VesiY';--1

**Comment by cedricbriandgithub** [comment]
database edition 2021 line 1134

**Comment by elfunesto** [comment]
Fixed: a new was missing in the function (NEW.geom): here is the sql used command to fix. If needed, you can run the update command that had been fired


CREATE OR REPLACE FUNCTION datawg.update_coordinates()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
NEW.ser_x = st_x(NEW.geom);
NEW.ser_y = st_y(NEW.geom);
RETURN NEW;
END;
$function$
;
