### ISSUE TITLE
Anguillicola

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#196]
We'll need to include anguillicola in next year datacall
presence absence
mean prevalence.
create new types 

=> one of the problems is that prevalence will have to be constrained to % or boolean
=> makes sense as it is per emu. Is that wise ?
=> Do you really want per emu. How do you calculate a percentage per emu where what you can really have is an index of sites (points) where you measure the prevalence and presence ?

**Comment by elfunesto** [comment]
for the 1st point: we can manage with triggers
for the 2nd: not sure, depends on the questions. I think we will want soon more precise values
for the 3rd: agree with you, I would tend to think that it should be better suited in biometry data, related to a monitoring site

**Comment by Cyclolumpus** [comment]
The objective is to draw a map that may highlight places where it is absent/low prevalence (i.e. coastal areas, limits of the distribution). Yes, you are right: EMU doesn't really make sense.
If it's included in biometry, this means it will become a "series" right?

**Comment by cedricbriandgithub** [comment]
Yes currently we report series for biometries but there is a table that is intended to store biometry data. But I'm not too fond of trying to squeeze in some data in some of the tables if they don't have the right format. So for me these data should be a 
x
y
Year
type (prevalence anguillicola , occurence anguillicola, and there we can squeeze in more types)
value
habitat type (T,C, F, MO)
EMU (to check when points are outside the emu somewhere in bengladesh that things went wrong)
geometry (point) derived from coordinates

The main difference between this table and the other is that it is not EMU based.

**Comment by elfunesto** [comment]
Just another thought, we are speaking of anguillicola, but we will probably have similar requests in the years to come for contaminants (see recommendation of SG5 about quality), and with contaminants, first PCB, AHP, but then the list of pollutants is likely to change over time with emerging contaminants. We might take this into consideration to build a solution flexible enough

**Comment by cedricbriandgithub** [comment]
Yes using type allows to introduce anything we want.
