### ISSUE TITLE
meta-documentation of data file handling

### ISSUE THREAD

**Issue by WillemXDekker** [ices-eg/wg_WGEEL#20]
Data call files coming in, we have to check them, create a corrected version, load them into the database, compare them to older data. So there are potentially four versions of the data. We need a meta-documentation of what has come in, who checked, etc etc. 
Currently, some data were missing, that had been submitted - and nobody could indicate what happened.
A log-file is not sufficient, since that would require a full analysis of past actions, for rather simple questions. And non-submission, or lack of follow-up action, would be implicitly coded.
Either integrate in the data-handling (best but lot of work), or develop an external meta-documentation of data-handling (a simple excel sheet, of requested files by country, indicating stage of data processing).

**Comment by cedricbriandgithub** [comment]
| log_data | log_evaluation_name | log_main_assessor | log_secondary_assessor | log_date |
| --- | --- | --- | --- | --- |
| catch_landings | data check | Willem Dekker | Cedric Briand | 208-07-30 |

where log_data is one of

 *   catch_landings
  *  release
  *  aquaculture
  *  biomass
  *  potential_available_habitat
  *  silver_eel_equivalents
  *  mortality_rates
  *  manual data correction

log_evaluation_name should correspond to

*  data check
*  duplicates choice
*  new data integration
*  data edition 

The main assessor is most often the national correspondent, the secondary assessor is someone with access to the database via the shiny application in the data subgroup

![image](https://user-images.githubusercontent.com/26055877/43420404-d8e7aa28-9443-11e8-9265-f7af7a65f22d.png)

**Comment by cedricbriandgithub** [comment]
I think this is the easiest way, did I miss anything ?

**Comment by cedricbriandgithub** [comment]
"log_id" || "log_cou_code" || "log_data" || "log_evaluation_name" || "log_main_assessor" ||"log_secondary_assesor" || "log_contact_person_name" || "log_method" || "log_message" || "log_date"
2 || "VA" || "catch_landings" || "check data" || "Cedric Briand" || "Cedric Briand" || "" || "Commercial data are retrieved from fisheries statistics." || "catch and landings
