### ISSUE TITLE
emu for NL

### ISSUE THREAD

**Issue by elfunesto** [ices-eg/wg_WGEEL#201]
Netherlands had reported landings using EMU NL_total while using NL_Neth for biomass and mortality indicators. For consistency, I modified to NL_total for all data types, but I think NL_Neth would be more appropriate?

**Comment by cedricbriandgithub** [comment]
country total to be used when unallocated

**Comment by mariazti** [comment]
To modify NL_total in "t_eelstock_eel" table: 
update datawg.t_eelstock_eel set eel_emu_nameshort = 'NL_Neth' where eel_cou_code = 'NL';   -- 538 rows (local db)
Should I modify other tables for this code?
