### ISSUE TITLE
Create template for datacall

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#204]
* [x] Annex 1
* [x] Annex 2
* [x] Annex 3
* [x] Annex 4
* [x] Annex 5
* [x] Annex 6
* [x] Annex 7
* [x] Annex 8
* [x] Annex 9 => new template for DCF, should refer to tables 
 t_samplinginfo_sai
 t_qualitygroup_qug and t_biometrygroup_bug

related issue #104 #188

**Comment by cedricbriandgithub** [comment]
the tabs will be named
sampling_info
new_grouped_data
updated_grouped_data
deleted_grouped_data
new_individual_data
updated_individual_data
deleted_individual_data

**Comment by cedricbriandgithub** [comment]
In series, explain distance to the sea (this is for Tea)

**Comment by cedricbriandgithub** [comment]
@elfunesto you add columns gr_id & grser_ser_id & gr_last_update & gr_dts_datasource in new_group_metrics ? They are not in the template, so this is inserted by your join am I right ? These should be left empty at this stage.
I can adapt the load_function easily for this, just to check with you
![image](https://user-images.githubusercontent.com/26055877/169642997-ec880d45-edd0-4178-a3df-c6cd75455804.png)

**Comment by elfunesto** [comment]
Normally, I  use the format specified in the root template, so if you prefer, we can just remove the column in the root template.  Currently, there is an instruction to leave it empty in the readme anyway.
-------- Message d'origine --------De : Cédric Briand ***@***.***> Date : 21/05/2022  10:26  (GMT+01:00) À : ices-eg/wg_WGEEL ***@***.***> Cc : elfunesto ***@***.***>, Mention ***@***.***> Objet : Re: [ices-eg/wg_WGEEL] Create template for datacall (Issue #204) 
@elfunesto you add columns gr_id & grser_ser_id & gr_last_update & gr_dts_datasource in new_group_metrics ? They are not in the template, so this is inserted by your join am I right ? These should be left empty at this stage.
I can adapt the load_function easily for this, just to check with you

**Comment by cedricbriandgithub** [comment]
Now this is the reason for my question, it should not be there.
![image](https://user-images.githubusercontent.com/26055877/169699160-2dd36d35-e2aa-45a1-8524-38e55bae72d7.png)

As said above, you can ignore that comment, these columns will be overridden and ignored anyway.

**Comment by elfunesto** [comment]
ok, fixed: I was using the format of existing_metric (where gr_id is present) for both existing_metric and new_metric. I will upload and checking revised prefilled templates by the end of the morning

**Comment by Teica12** [comment]
> In series, explain distance to the sea (this is for Tea)

It is already in the readme tab, but I have included it under series_info as well.

**Comment by cedricbriandgithub** [comment]
@elfunesto 

das_dts_datasource is missing in updated_data and deleted data : what do we do ?

**Comment by cedricbriandgithub** [comment]
I think it is preferable to have it in existing data, since that information is present in the db, and copy it to updated and deleted data, currently we are generating the datasource in load series for new
```r
	  # for updated data and deleted data 
		if (grepl("data", sheet) & grepl("new", sheet)) {
			data_xls$das_dts_datasource <- datasource
		}		
		if (grepl("group", sheet)  & grepl("new", sheet)) {
			data_xls$gr_dts_datasource <- datasource
			data_xls$meg_dts_datasource <- datasource
		}
		if (grepl("individual", sheet)  & grepl("new", sheet)) {
			data_xls$gr_dts_datasource <- datasource
			data_xls$mei_dts_datasource <- datasource
		}
```

Later on we don't use this column in checking for modifications so it doesn't really matter what we have there, just that then we will be returning that info to the user.
```r
	modified <- dplyr::anti_join(data_from_excel, data_from_base, 
			by = c("das_year", "das_value", "das_comment", "das_effort", "das_ser_id")
	)

So Im' changing my sheet to add it, (in the example FR you sent me).
```

**Comment by cedricbriandgithub** [comment]
@elfunesto Again another problem detected, please rename column gr_ser_id to grser_ser_id in updated and deleted data in series template

**Comment by cedricbriandgithub** [comment]
@elfunesto delete column gr_id in new group metrics, it is not created yet
