### ISSUE TITLE
Shiny integration for DCF data

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#205]
After preparing the db #104
We need to develop the integration in shiny

**Comment by cedricbriandgithub** [comment]
In Sampling_info table, remove sai_locationdescription : I don't see the point at the emu scale
Q : sai_sam_gear : do we really mean to have only one sampling gear per sampling scheme ????

**Comment by Teica12** [comment]
> In Sampling_info table, remove sai_locationdescription : I don't see the point at the emu scale Q : sai_sam_gear : do we really mean to have only one sampling gear per sampling scheme ????

I agree, we can remove these columns from sampling_info.
