### ISSUE TITLE
Problem with sampling gear table

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#212]
![image](https://user-images.githubusercontent.com/26055877/168631139-9744e1c2-6ecf-44ed-92e4-90f6645692ba.png)

What is in the second column ?

**Comment by elfunesto** [comment]
![image](https://user-images.githubusercontent.com/43066644/168843777-123cca5d-8a34-43ba-bd65-7e2a1513c9f8.png)

a "poor translation of the FAO classification (https://www.fao.org/3/cb7393en/cb7393en.pdf) ?
