### ISSUE TITLE
problem in template for landings

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#217]
reported by @ciaraoleary

the annex 4 commercial catch in the new data tab the value column has a validation list applied asking for missing values nr,nc etc and the missing data column has a list asking for emu code

@Teica12 
In Annex 4, check wrong expanded to the first eight columns, again restricting the entry of the landings value as well.

**Comment by elfunesto** [comment]
We have removed most data checks since they cause more trouble than they solve
