### ISSUE TITLE
recreational catch is marked as deprecated

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#218]
7	rec_catch_kg	Recreational catch (kg) DEPRECATED	kg

This is not consistent with the readme from datacall

Recreational Landings should include any eel taken from the water by recreational fisheries. Recreational Discards is any eel that are caught but then returned alive to the location where they were caught – we would call this ‘catch and release’ but Release is a term used already for eel that are moved to another location. Landings + Discards = total Catch, analogous to the marine commercial fisheries situations.  

So change definition

**Comment by cedricbriandgithub** [comment]
I guess we don't have to worry too much for that one given the new EU rule ? Suggest close without doing anything ? or change the definition for the template this year and keep it simple.

**Comment by elfunesto** [comment]
I updated the readme to simplify the template
