### ISSUE TITLE
DATA CALL 2022 spreadsheets : data check wrong in annex 4 5 6 7 8 

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#219]
# This bug is affecting all of you and has been reported by many users, sorry for that !
* [X] For Annex 4, 5, 6 & 7, under new data tab, first two columns seem to be the wrong way round with eel_type_name suggesting a year if you hover on it and eel_year suggesting kg, thus making it hard to fill in given the restrictions.

* [X] In addition, in Annex 6 & 7, under new_data tab, orange boxes indicate that here we will have all the missing data extracted, including pre-filled new data we need to enter for 2022, as per Annex 4 and 5, but the tab is empty, nothing has been extracted.

**Comment by cedricbriandgithub** [comment]
Solution : dop data checks 
![image](https://user-images.githubusercontent.com/26055877/184127608-c09380f3-cbf7-4774-80bc-949baba5a256.png)

**Comment by elfunesto** [comment]
fixed templates are now in the sharepoint
