### ISSUE TITLE
Link database ID to provider ID for individual data

### ISSUE THREAD

**Issue by jdpo** [ices-eg/wg_WGEEL#220]
To provide potential updates on individual eel data we need to establish a link between the Eel ID of the provider and the ID given to it in the DB. Easiest would be to add a column with "provider ID" in the data call sheet. This would also solve other issues (like reporting a fish twice in individual data, while maintaining the info that it is the same fish, since it might belong to several group_info)

**Comment by elfunesto** [comment]
fix with commit fae91f3b9be062fa210fedeca4305b1ba6f59727
