### ISSUE TITLE
fi_last update is missing an underscore

### ISSUE THREAD

**Issue by jdpo** [ices-eg/wg_WGEEL#221]

**Comment by jdpo** [comment]
...and pectoral_lengthmm as well ;)

**Comment by cedricbriandgithub** [comment]
where ? In excel ?

**Comment by jdpo** [comment]
Yes, don't worry. It's just some smaller inconsistencies in the spreadsheets and I didn't want to forget;) 


Von: "Cédric Briand" ***@***.***> 
An: "ices-eg/wg_WGEEL" ***@***.***> 
CC: "Jan-Dag Pohlmann" ***@***.***>, "Author" ***@***.***> 
Gesendet: Mittwoch, 17. August 2022 13:32:39 
Betreff: Re: [ices-eg/wg_WGEEL] fi_last update is missing an underscore (Issue #221) 





where ? In excel ?

**Comment by cedricbriandgithub** [comment]
Good to have it marked. It might cause problems when trying to import in shiny

**Comment by elfunesto** [comment]
fix in template
