### ISSUE TITLE
Issue with fi_date

### ISSUE THREAD

**Issue by jdpo** [ices-eg/wg_WGEEL#222]
fi_date is problematic (for germany, but probably for many others too) since 1. fish are not always sampled on the day they are caught but often frozen; I think we should refer to catch date here and 2. if providing a catch data this can often be a period when sampling commercial fisheries where fishermen collect eels for the DCF. Especially day is a resolution that will likely never be needed and it could be set to a default of 15, when fished across a month boundary we need to define whether to use earlier or later month. We did it like this and use the earlier month... Maybe in these cases one could use day 31 (but I wouldn't make things unneccessarily complicated - 15 days won't be a big source of error I guess?)

**Comment by cedricbriandgithub** [comment]
Do we need to change the definition in the template ?

Suggest adding in comment that is never read anyways catch date.  Do we need to be super precise on the date definition, I guess we'll collect what's in the db ?

**Comment by elfunesto** [comment]
I updated the template and put "Date of sampling - this should correspond to the date when the fish was caught - be as precise as possible"
