### ISSUE TITLE
definition of sex

### ISSUE THREAD

**Issue by jdpo** [ices-eg/wg_WGEEL#223]
we do not define how to differentiate sex, this could for silver eel also be done by silvering index...

**Comment by cedricbriandgithub** [comment]
This applies to female proportion in group sex, is female, is differenciated. For fat there are two different columns (corresponding in fact to different mei_id. I don't really see any other way than to associate a method to a new metric ?

**Comment by cedricbriandgithub** [comment]
Too difficult to implement.
