### ISSUE TITLE
Annex 10 deleted data not handled

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#234]

**Comment by cedricbriandgithub** [comment]
fixed by hilaire

**Comment by cedricbriandgithub** [comment]
@elfunesto  I didn't find a commit for this have you finished ?
Ciara will send us some files to fix

**Comment by elfunesto** [comment]
No, I just did with an sql query pasted on darabase_edition_2022.sql
-------- Message d'origine --------De : Cédric Briand ***@***.***> Date : 07/09/2022  16:30  (GMT+01:00) À : ices-eg/wg_WGEEL ***@***.***> Cc : elfunesto ***@***.***>, Mention ***@***.***> Objet : Re: [ices-eg/wg_WGEEL] Annex 10 deleted data not handled (Issue #234) 
@elfunesto  I didn't find a commit for this have you finished ?
Ciara will send us some files to fix

**Comment by elfunesto** [comment]
I think the facility was developed at the end of the WGEEL: there is function to delete group and individidual metric in importdcfstep1 and importdcfstep2

**Comment by cedricbriandgithub** [comment]
to be tested next year during data integration
