### ISSUE TITLE
Annex 2 cant update group metrics

### ISSUE THREAD

**Issue by jdpo** [ices-eg/wg_WGEEL#239]
cant integrated, Error: Anenex 2could not find function "update_group_metrics"

**Comment by jdpo** [comment]
Same issue for Annex 1:
First integration error:Error: Failed to prepare query: ERROR:  column "gr_number" is of type integer but expression is of type boolean
LINE 2: (SELECT g.gr_year,g.gr_number,g.gr_comment,g.gr_dts_datasour...
                          ^
HINT:  You will need to rewrite or cast the expression.

During re-integrating error changed to:

could not find function "update_group_metrics"

**Comment by cedricbriandgithub** [comment]
should be fixed
