### ISSUE TITLE
Annex 1 no check on ser_effort_uni_code

### ISSUE THREAD

**Issue by jdpo** [ices-eg/wg_WGEEL#241]
if a wrong unit is entered it is only shown when integrating but not when checking the file. Easy to workaround, but could be changed.

**Comment by elfunesto** [comment]
This is weird: in loading_functions, we check that 
```
		data_error <- rbind(data_error, check_values(
						dataset=series,
						namedataset= "series_info",
						column="ser_effort_uni_code",
						country=country,
						values=tr_units_uni$uni_code))	
```

and 

tr_units_uni is collected from the db in server.R with
```
query <- "SELECT * from ref.tr_units_uni"
						tr_units_uni <<- dbGetQuery(pool, sqlInterpolate(ANSI(), query))   
```

Can you give me an example file so that I can check what happens?

**Comment by jdpo** [comment]
I'll have to check (maybe I only have the corrected version). Since it is not urgent and can be dealt with, I'll see to it later or tomorrow.
