### ISSUE TITLE
check duplicates completely wrong

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#242]
The column names are wrong in replaced
query0_reverse will not work as it is many lines
This needs to be reprogrammed
This affects annex 4 to 8

**Comment by elfunesto** [comment]
is it in the check duplicate or in the write_duplicate? I can have a look tomorrow. Anyway, we should better move to a dbBegin and dbCommit instead of using reverse query, it would greatly simplify the code.

**Comment by cedricbriandgithub** [comment]
For some reasons, the dbExecute does not return rows. not adapted to percent eel stock
