### ISSUE TITLE
Annex 10, individual metrics

### ISSUE THREAD

**Issue by jdpo** [ices-eg/wg_WGEEL#244]
When trying to integrate the new individual metrics file ERROR:

Error: Failed to fetch row: ERROR:  null value in column "fisa_lfs_code" violates not-null constraint
DETAIL:  Failing row contains (325321, 2011-08-15, 2011, 322_Date is not exact and refers to the landing date. Day was al..., 2022-09-07, dc_2022, 212, null, null, null, null).

 There is no null value in lfs_code (its always S or Y) and the detail points to the first row, so I suppose it is something general but it never gets to the second row.

HOWEVER, this is using a previously generated "new_individual metrics" file (which should not have changed), when trying to re-create it I cannot read the Annex at all, I get an error "sheet 9 has 26 columns, but 'col_types' has length 25 (guess due to addition of fi_year - but didn't have the error yesterday though fi_year was in there as well). Error in a red box on bottom left.

**Comment by elfunesto** [comment]
Same error with GB, I am going to check now.

**Comment by elfunesto** [comment]
@jdpo should be fixed, can you have a try?
