### ISSUE TITLE
Annex 5 Error when checking duplicates for Recreational landings

### ISSUE THREAD

**Issue by pbernotas** [ices-eg/wg_WGEEL#246]
Hey, I receive this error when I try to check duplicates on the table uploaded (under catch and landings): 

"There is a mismatch between selected typ_id 7;6 and the dataset loaded from base 4;6;32;33 did you select the right File type ?"

**Comment by cedricbriandgithub** [comment]
Yes that's an error with the automatic integration. Please delete the lines marked as recreational catch
