### ISSUE TITLE
Annex 8, cant integrate single "NR" row

### ISSUE THREAD

**Issue by jdpo** [ices-eg/wg_WGEEL#249]
gives the following error:

Error: Failed to fetch row: ERROR:  new row for relation "t_eelstock_eel" violates check constraint "ck_qal_id_and_missvalue"
DETAIL:  Failing row contains (549730, 11, 2021, null, LT_total, LT, Y, null, null, 0, null, not reported due to commercial confidentiality reasons, 2022-09-08, NR, dc_2022, Public).

single line, no value, missvaluequal = NR

**Comment by cedricbriandgithub** [comment]
Yes that's the new constraint, if you choose NR you cannot have qal_id 0 put a 1 instread.
