### ISSUE TITLE
Update dataseries for year

### ISSUE THREAD

**Issue by LBeaulaton** [ices-eg/wg_WGEEL#255]
when trying to update get:
`Error: Failed to fetch row: ERROR:  duplicate key value violates unique constraint "c_uk_year_ser_id"
DETAIL:  Key (das_year, das_ser_id)=(1982, 220) already exists.`

while there is only 1  data for this year

**Comment by elfunesto** [comment]
As seen with Laurent, this is not truly a bug. Laurent will try to make the update with a workaround

**Comment by LBeaulaton** [comment]
error is due to a whole series (das_ser_id = 220) that need to be updated because the season has been wrongly attributed to n+1 instead of n. I have first deleted the whole series and then inserted again the new series.

**Comment by LBeaulaton** [comment]
![image](https://user-images.githubusercontent.com/26081069/189621116-74d2c89c-0a01-4279-aa8f-91784406be4a.png)

**Comment by elfunesto** [comment]
This lattest bug was fixed: it happens when both updated and new are empty, might also occur in importdcfstep1

**Comment by LBeaulaton** [comment]
still error : multi-argument returns are not permitted
