### ISSUE TITLE
ANNEX 3 (LT): cant integrate new group metrics

### ISSUE THREAD

**Issue by jdpo** [ices-eg/wg_WGEEL#259]
following error when trying to integrate: Error: Failed to fetch row: ERROR:  duplicate key value violates unique constraint "c_ck_uk_grser_gr"
DETAIL:  Key (grser_ser_id, gr_year)=(350, 2021) already exists.

**Comment by elfunesto** [comment]
I think you try to enter two groups with two different life stages? Till now, it is allowed for sampling but not for series. Should we allow it for series? It might be convenient to have biometry life stages convenient with the time series ?
