### ISSUE TITLE
deal with eel_value_number and eel_value_kg in annex 3 Realease

### ISSUE THREAD

**Issue by SabineAllou** [ices-eg/wg_WGEEL#26]
1/ check function "check_missvalue_release" is created in checking_utilities
2/ separate data between kg and number 
3/ add type_id 8 or 9 to the corresponding line
4/ Rbind data in the same data frame to import in database
5/ Add "ND" in eel_missvaluequal if one value is still missing

**Comment by SabineAllou** [comment]
One way (maybe not the most elegant) to do it : 

`#tibbles are weird, change to dataframe`
`release <- as.data.frame(release)`

`#separate data between number and kg`
`#create data for number and add eel_typ_id 9`
`release_N <- release[,c(1,2,3,5,6,7,8,9,10,11)]`
`release_N$eel_typ_id <- rep(9, nrow(release))`
`colnames(release_N)[colnames(release_N)=="eel_value_number"] <- "eel_value"`

`#create data for kg and add eel_typ_id 8`
`release_kg <- release[,c(1,2,4,5,6,7,8,9,10,11)]`
`release_kg$eel_typ_id <- rep(8, nrow(release))`
`colnames(release_kg)[colnames(release_kg)=="eel_value_kg"] <- "eel_value"`

`Rbind data in the same data frame to import in database`
`release_tot <- rbind(release_N, release_kg)`
`release_tot<-release_tot[,c(11,1,2,3,4,5,6,7,8,9,10)]`

`#Add "ND" in eel_missvaluequal if one value is still missing`
`for (i in 1:nrow(release_tot)) {`
`  if (is.na(release_tot[i,4])) {`
`    release_tot[i,5] <- "ND"`
`  }`
`}`

**Comment by SabineAllou** [comment]
in datacall file "release", eel_typ_name asks for numbers even thought both eel_value_n and ee_value_kg have to be filled.
rename ee_typ_name with the correct name (n or kg) after splitting data

**Comment by cedricbriandgithub** [comment]
OK : This is when you load the excel table, ticket  #33 is for loading data from the database.

**Comment by SabineAllou** [comment]
Ok I got it ! I just noticed this mistake while checking for loading data
