### ISSUE TITLE
Annex 2 (yellow eel for GB): Not all data under deleted series data show when checking for duplicates

### ISSUE THREAD

**Issue by Teica12** [ices-eg/wg_WGEEL#260]
[2022 DC WGEEL UK TIME SERIES YELLOW STANDING STOCK map.xlsx](https://github.com/ices-eg/wg_WGEEL/files/9537105/2022.DC.WGEEL.UK.TIME.SERIES.YELLOW.STANDING.STOCK.map.xlsx)

**Comment by elfunesto** [comment]
Should be also fixed, can we have a try on monday?

**Comment by Teica12** [comment]
I have tried and I can now see all deleted data, but I have the same issue as with Annex 1 & 3, so for deleted series error is dataseries_temp not found and for updated and deleted group metrics: multi-argument returns are not permitted.
We can try and sort out on Monday, might be easier.
Btw I now get updated and new group metrics under modified group metrics, which is strange, I deleted the new ones but still does not work.

[modified_group_metrics_yellow_eel_2022-09-11_GB.xlsx](https://github.com/ices-eg/wg_WGEEL/files/9543007/modified_group_metrics_yellow_eel_2022-09-11_GB.xlsx)
[deleted_group_metrics_yellow_eel_2022-09-11_GB.xlsx](https://github.com/ices-eg/wg_WGEEL/files/9543008/deleted_group_metrics_yellow_eel_2022-09-11_GB.xlsx)
[deleted_dataseries_yellow_eel_2022-09-11_GB.xlsx](https://github.com/ices-eg/wg_WGEEL/files/9543009/deleted_dataseries_yellow_eel_2022-09-11_GB.xlsx)

**Comment by Teica12** [comment]
I have tried and I can now see all deleted data, but I have the same issue as with Annex 1 & 3, so for deleted series error is dataseries_temp not found and for updated and deleted group metrics: multi-argument returns are not permitted.
We can try and sort out on Monday, might be easier.
Btw I now get updated and new group metrics under modified group metrics, which is strange, I deleted the new ones but still does not work.

[modified_group_metrics_yellow_eel_2022-09-11_GB.xlsx](https://github.com/ices-eg/wg_WGEEL/files/9543007/modified_group_metrics_yellow_eel_2022-09-11_GB.xlsx)
[deleted_group_metrics_yellow_eel_2022-09-11_GB.xlsx](https://github.com/ices-eg/wg_WGEEL/files/9543008/deleted_group_metrics_yellow_eel_2022-09-11_GB.xlsx)
[deleted_dataseries_yellow_eel_2022-09-11_GB.xlsx](https://github.com/ices-eg/wg_WGEEL/files/9543009/deleted_dataseries_yellow_eel_2022-09-11_GB.xlsx)

**Comment by elfunesto** [comment]
should be fixed with #261 resolution
