### ISSUE TITLE
Annex 1 & 3 (GB): can not upload deleted data series: Error: 'deleted_dataseries_temp' not found.

### ISSUE THREAD

**Issue by Teica12** [ices-eg/wg_WGEEL#261]
[deleted_dataseries_silver_eel_2022-09-09_GB (2).xlsx](https://github.com/ices-eg/wg_WGEEL/files/9537150/deleted_dataseries_silver_eel_2022-09-09_GB.2.xlsx)
[deleted_dataseries_glass_eel_2022-09-09_GB (3).xlsx](https://github.com/ices-eg/wg_WGEEL/files/9537151/deleted_dataseries_glass_eel_2022-09-09_GB.3.xlsx)

**Comment by elfunesto** [comment]
This one was normally fixed on Friday late. Can you check please?

**Comment by Teica12** [comment]
Does not work for me, same error for again for deleted data series
For updated group metrics, deleted
[Uploading deleted_dataseries_silver_eel_2022-09-11_GB (1).xlsx…]()
 and updated I get:  multi-argument returns are not permitted

**Comment by elfunesto** [comment]
Sorry, it seems that a git conflict has deleted the fix, will correct it
