### ISSUE TITLE
modify import_to_database to allow testing outside shiny application

### ISSUE THREAD

**Issue by SabineAllou** [ices-eg/wg_WGEEL#28]
This script was developped during wgeel 2017, it was running as a standalone script importing all files from all countries. In 2018 the wkteel decided to leave the import in the hands of the wgeel member through the shiny application. For this reason, each file will be processed separately (e.g. Danemark will import the aquaculture file, check for errors and duplicates, and then integrate it through the shiny application. Hence, the long script file is no longer needed but it should be updated to allow to test the functions outside from shiny and use as a backup.
https://github.com/ices-eg/wg_WGEEL/blob/master/R/stock_assessment/import_to_database.R

**Comment by cedricbriandgithub** [comment]
Won't do
