### ISSUE TITLE
Recruitment : track effect of recent series inclusion 

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#280]
basically an overlay of the last five years recruitment index graphs to give an idea of the effect of changing time series. @jdpo we won't forget it's there now. !

**Comment by elfunesto** [comment]
To do so, do we need to have a table which lists the data series used every year? A table wgeel_model with 3 columns:
mod_year: year of the model
mod_model: type of the model (glm glass eel, glm yellow...)
mod_ser_nameshort: the ser_nameshort of a series that was selected.

**Comment by elfunesto** [comment]
Three tables have been developed to keep track of what is done: on ref that contraints the types of model, one modelrun that contains information on a specific run of the model (there can be multiple per year) and one that contains the datapoint (das_id) related to the modelrun.

**Comment by elfunesto** [comment]
no, we need to develop the export for the recruitment analysis
