### ISSUE TITLE
Annex 7 Releases eel_type_name should be release_n not q_release_n 

### ISSUE THREAD

**Issue by ciaraoleary** [ices-eg/wg_WGEEL#283]
got error when checking file the tr_typeseries_typ name was wrong wanted release_n not q_release_n

this was explained in metadata tab but the existing data had q_release_n

C

**Comment by cedricbriandgithub** [comment]
check the template and the value in db and test

**Comment by cedricbriandgithub** [comment]
OK got it. You need to fill in release_n as the program with then assign the column number to q_release_n and the column eel_value_kg to q_release_kg. So this is expected it's not a bug.
Changes to make the template more clear.
![image](https://github.com/ices-eg/wg_WGEEL/assets/26055877/38696b89-8999-425e-9fb8-281b63108d68)

**Comment by cedricbriandgithub** [comment]
Done there
