### ISSUE TITLE
Relabel "True and False" to "Raw and Predicted"

### ISSUE THREAD

**Issue by ciaraoleary** [ices-eg/wg_WGEEL#31]
For the predicted and raw graphs there is a graph indicating where the predicted data is used but the label refers to true and false and can be mis interpreted. Change label to raw and predicted.

**Comment by ClarisseBoulenger** [comment]
I've done the change but I changed also the legend title from "original data" to "Data" is it ok for everyone

**Comment by ciaraoleary** [comment]
That's great thanks Clarisse
