### ISSUE TITLE
fix biometry metric

### ISSUE THREAD

**Issue by elfunesto** [ices-eg/wg_WGEEL#319]
there are still:
- inconsistencies between templates headings and metrics in the db
- inconsistent formatting of metric name in the db (e.g. "Female proportion (from gonads)" while we never use capital letter nor white space)

**Comment by cedricbriandgithub** [comment]
For example in 2024 :
•	the template had column name "is_female_(1=female,0=male)", it is "is_female(1=female,0=male)" in the db
•	the template had column "eye_diam_mean_mm" while it is in " eye_diam_meanmm" in the db
•	the template had column "anguillicola_presence(1=present,0=absent)" while it should be "anguillicola_presence_visual(1=present,0=absent)"

**Comment by cedricbriandgithub** [comment]
OK, problem of updating the server, fixing this

**Comment by cedricbriandgithub** [comment]
```sql
UPDATE "ref".tr_metrictype_mty
  SET mty_name='female_proportion'
  ,mty_individual_name='is_female(1=female,0=male)'
  ,mty_description='Female status (is_female) or female proportion in the population female/(male+female) for group'
  ,mty_method='Check method in method_sex'
  WHERE mty_id=6;

UPDATE "ref".tr_metrictype_mty
  SET mty_name='anguillicola_proportion'
  ,mty_individual_name='anguillicola_presence(1=present,0=absent)'
  ,mty_description='Presence of anguillicola or prevalence in proportion in group (between 0 and 1)'
  ,mty_method='check method in method_anguillicola'
  WHERE mty_id=8;


UPDATE "ref".tr_metrictype_mty
  SET mty_name='method_sex_(1=visual,0=use_length)'
  ,mty_individual_name=NULL
  ,mty_description='Method used for sex determination'
  ,mty_method=NULL
  WHERE mty_id=27;

UPDATE "ref".tr_metrictype_mty
  SET mty_name='method_anguillicola_(1=stereomicroscope,0=visual_obs)'
  ,mty_individual_name=NULL
  ,mty_description='Method used for sex determination'
  ,mty_method=NULL
  WHERE mty_id=28;
```

**Comment by cedricbriandgithub** [comment]
note we will still need to update reference tables in templates for next datacall but this should be automatic (using the update_referential_sheet function)
