### ISSUE TITLE
Annex 1: Disconnects when "validate" updated series

### ISSUE THREAD

**Issue by jdpo** [ices-eg/wg_WGEEL#330]
[modified_series_glass_eel_2024-09-09_DE.xlsx](https://github.com/user-attachments/files/16930326/modified_series_glass_eel_2024-09-09_DE.xlsx)

**Comment by elfunesto** [comment]
This was due to an issue with idle_timeout. This should be fixed with commit 9a1048a0e7d4bedddb4eb732ad575c1c2b13e0a2
The file was also integrated
