### ISSUE TITLE
qual_id in annex 10 et 11

### ISSUE THREAD

**Issue by GuirecAndre** [ices-eg/wg_WGEEL#342]
at step 2 of the integration, I have the following message : 
_Error: Failed to fetch row: ERROR:  new row for relation "t_eelstock_eel" violates check constraint "ck_qal_id_and_missvalue"
DETAIL:  Failing row contains (573962, 34, 2007, null, FR_Adou, FR, S, AL, null, 0, null, null, 2024-09-10, NR, dc_2024, Public)._

![image](https://github.com/user-attachments/assets/c33a6410-6c3b-4217-bebc-ebe4e89c5a5e)

annex 10 : 
[2024_Eel_Data_Call_Annex10_Biomass_Indicators_FR.xlsx](https://github.com/user-attachments/files/16945823/2024_Eel_Data_Call_Annex10_Biomass_Indicators_FR.xlsx)

Note that the sheet 'existing_kept' is empty.

file for new_data produced after step 1 : 
[new_biomass_2024-09-10FR.xlsx](https://github.com/user-attachments/files/16945845/new_biomass_2024-09-10FR.xlsx)

**Comment by elfunesto** [comment]
For existing_kept: we don't have mortality and biomass for France since France didn't answer to WKEMP3 datacall
