### ISSUE TITLE
add eel_typ_id column before importing to database ?

### ISSUE THREAD

**Issue by SabineAllou** [ices-eg/wg_WGEEL#36]
in most files of the 2018 datacall, the eel_typ_id has been deleted to avoid mistakes. Do we have to create this column after loading the excel file and fill it with the corresponding id before importing the data to the database, as the database needs eel_typ_id ? 

(it's already done for the release file after splitting data between N and KG)

**Comment by cedricbriandgithub** [comment]
I had not realised this yet, as I was dealing with merge from the database and the xls file and still had the typ available.
We have to create a small function which takes for input any dataset with a typ_name and collects the tr_typeserie_typ data from the database using [extract_ref](https://github.com/ices-eg/wg_WGEEL/blob/069d63a8663bf6a90e3ea13cb24e839804be211f/R/database_interaction/database_reference.R#L13), it will create the column

**Comment by SabineAllou** [comment]
See function [match_typ_id](https://github.com/ices-eg/wg_WGEEL/blob/master/R/utilities/match_typ_id.R). I didn't know where to write it, maybe in check_utilities ? 

Also, I didn't succeed to connect with the database with database_connection, so can you try to see if it's working with extract_ref ? 
If so, i will add match_typ_id to every loading functions.

**Comment by cedricbriandgithub** [comment]
I used 
  if (!exists("tr_type_typ")) {
    extract_ref('Type of series')
  }
and 
  tr_type_typ_for_merge<-tr_type_typ[,c("typ_id","typ_name")]
  colnames(tr_type_typ_for_merge)<-c("eel_typ_id","eel_typ_name")
