### ISSUE TITLE
new codes for eel_typ_name needed, for Assisted Migration and Trap & Transport

### ISSUE THREAD

**Issue by WillemXDekker** [ices-eg/wg_WGEEL#37]
To deal with Restocking, Assisted Migration, and Trap & Transport, we decided to split each of them up into two separate events:
1. The catch of an eel, for the purpose of Restocking etc.
2. The release of the same eel, at another place.
The issue is about the catch. We deal with that in "Catch and Landings", but that allows for com_landings_kg and rec_landings_kg only. How to consider an elver-trap below a hydrostation? That is neither commercial nor recreational (legally speaking), so it would be confusing to report them as such.
Suggestion: add codes for all other catches, "other_landings_kg" and "other_landings_N", adding a comment that the exact purpose can be described in the corresponding eel_comment. 
The templates need to be adapted for this (Willem will do, on WKTEEL sharepoint, and check WGEEL sharepoint),
and the data reading code (Cedric?).

**Comment by WillemXDekker** [comment]
Willem has updated templates on WKTEEL sharepoint. 
Remaining problem: this will not propagate into the 2018 data-call automatically. Do we ask ICES (DavidM) to update? No, let's wait for other issues today. I am working on upload of Swedish data, and might find more problems.

**Comment by SabineAllou** [comment]
if so, to load the data to the database, we have to :  
- rename com_landinds_kg and rec_landings_kg to c_landings_kg and r_landings_kg to match the database
- add other_landings_kg and other_landings_N in check_values for load_catch_landings
- add typ_name : "other_landings_kg" and "other_landings_N" in tr_typeseries_typ 
- add typ_id 6.1 and 6.2 in tr_typeseries_typ
