### ISSUE TITLE
pb with uppercase / lowercase in eel_typ_id

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#43]
Excel does not recognize lowercase uppercase, change all eel_typ_id to lowercase to avoid problems

**Comment by elfunesto** [comment]
corrected with commit 875795a289cb8b7b39f20c0e9f63d0df4a01b6f1

**Comment by mariazti** [comment]
"eel_type_name" in excel files are in lowercase with "correct_me" function, but in the database is still in uppercase when we compare with the database.
Two options are possible: 1. change the database to lowercase (check for the data visualization if it is ok), 2. when we use the "extract_ ref" function, change to lowercase the data from the database when need it

**Comment by SabineAllou** [comment]
The eel_type_name column in the reference table was change to lowercase to match the excel files values  after the "correct_me" function change them to lowercase
