### ISSUE TITLE
excel export in edit / shiny integration

### ISSUE THREAD

**Issue by LBeaulaton** [ices-eg/wg_WGEEL#44]
In shiny integration app / edit tab, create a excel button to export your table in excel format

**Comment by LBeaulaton** [comment]
add a filter field also

**Comment by elfunesto** [comment]
I added the excel export option with commit 4e3cdcc747e4cd4c90acc4b62eaafe763b348ff8

**Comment by elfunesto** [comment]
and a field seach is added "et voilà" f54d9abf7fccbd4b74782be28cc094f930096174
