### ISSUE TITLE
data integration : compare with database = potential problem

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#45]
When integrating the data into the database, the function `extract_data` is used. This function calls the view behind the scene which uses only qal id 1 2 and 4
Add a parameter allowing to choose which qal id is used with default ot  1 2 and 4
Change the views
```r
extract_data = function(data_needed, from_database=TRUE)
```

**Comment by cedricbriandgithub** [comment]
This is very important, otherwise we will be faced with duplicates next time !

**Comment by SabineAllou** [comment]
extract_data function have now two more arguments =
- quality, default is 1,2,4
- quality_check, default is TRUE. If True, the function does a selection on the eel_qal_id column with the quality argument

theses arguments were add to the function where it's used in data_integration and data_visualisation scripts. As theses functions use views, we had to correct them in view.sql and precodata.sql to make it works. 

the package 'glue' is used in the extract_data, so it has been add to the global script in data_visualisation (already in the global script in the data_integration)
