### ISSUE TITLE
Year for B0

### ISSUE THREAD

**Issue by LBeaulaton** [ices-eg/wg_WGEEL#51]
the database require a year for any data, including B0. Theoretically there is no sense to do that, even though some countries adjust there B0 to available habitat.
Currently the year is rather randomly chosen. This should be harmonised to allow to detect any duplicates

**Comment by LBeaulaton** [comment]
I propose to attribute to 1800 (round date that won't be used for anything else) B0 when it is unique. This standardization will allow to track any update of this value and ease the query of the database.
If for some reason a EMU want to have a changing B0 over the year they should provide a B0 for any year with a biomass and mortality.

to summarize 2 options:
1. unique B0 arbitrarily affected to 1800
2. B0 for every year

option 1 should be prefered.

**Comment by cedricbriandgithub** [comment]
OK,  but if duplicates are present how do you deal with this ?

**Comment by LBeaulaton** [comment]
currently in the database, 3 situations:
- only one value --> modify the date for 1800
- same B0 repeated every year --> should be qal_id = 18 and replace by a new data in 1800 being that B0
- B0 repeated over the years, be different values --> keep as it is, but the data provider should provide B0 each time

**Comment by LBeaulaton** [comment]
Instructions should be given accordingly for next data call

**Comment by cedricbriandgithub** [comment]
We should let that issue open untill 2021
