### ISSUE TITLE
How to propagate NR or NP to aggregation levels ....

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#61]
IF a NP is provided at an emu level, it is ignored when summing per country as otherwise we would end up only with NA value.

**Comment by ClarisseBoulenger** [comment]
I try something with a subset to delete NA just after the filtered data (to delete the NA produce when NP or NR in the database) in rendertable it seems to work but it's not a clean code  Ihave to look further to be sure

**Comment by cedricbriandgithub** [comment]
check if fixed with new datacall
