### ISSUE TITLE
Develop the rasta map

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#66]
integrate into shiny
one for country / one for emu, one option show last value
otherwise show values for the year highest in the slider
![image](https://user-images.githubusercontent.com/26055877/45599687-5ab68200-b9f0-11e8-9acf-7369399dea95.png)

**Comment by cedricbriandgithub** [comment]
This is wrong, log is OK to compare mortalities, but here we are looking at biomass, so I shift to sqrt

**Comment by cedricbriandgithub** [comment]
nothing is wrong with mortalities look it's all green ???
![image](https://user-images.githubusercontent.com/26055877/45600246-d79a2980-b9f9-11e8-9dbb-dcfdee2f46b6.png)

**Comment by elfunesto** [comment]
Pie chart are not necessarily a good representation and we already have barchart and rata maps that are working very well so I have remove this option
