### ISSUE TITLE
Reporting uncertainty around the GLM recruitment models?

### ISSUE THREAD

**Issue by AlanCefas** [ices-eg/wg_WGEEL#68]
ADGEEL 2018 asked why there are no uncertainties reported for the GLM analyses for glass eel and yellow eel recruitment series. We (Alan, Willem, Russell) explained that it was difficult/impossible to incorporate the uncertainty of all the individual series into a single model. This stopped the discussion for the moment but I can see it coming back, so can we agree a definitive answer please, or plan some work to address this issue? Thanks

**Comment by cedricbriandgithub** [comment]
The reason is that the value presented is the geometric means of predictions scaled to 1960-1970. It’s not the glm results. I can get the IC for one site. But not on the average values.

**Comment by LBeaulaton** [comment]
reported in the graph
