### ISSUE TITLE
Recruitment file, historical data Gironde 2004-2010

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#70]
Laurent :
Data 
(2004 --> 2010) :
need to be replaced by IRSTEA data from EDF report
 14.4 17.3 9.4 7.5 10.0 3.5 3.4

**Comment by LBeaulaton** [comment]
@elfunesto peux-tu stp vérifier les séries Gironde

**Comment by elfunesto** [comment]
@LBeaulaton we are currently working on the transect abundance indices. Hope to have a more reliable index this year
