### ISSUE TITLE
France ... provide values for 2009

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#73]
France did not provide values for 2009, those were not available due to management plan implementation, check what we do about that

**Comment by cedricbriandgithub** [comment]
note sent during datacall

**Comment by elfunesto** [comment]
We can potentially use wkeelmigration data with the following script

begin;
insert into datawg.t_eelstock_eel (eel_typ_id,
    eel_year,
    eel_value ,
    eel_emu_nameshort ,
    eel_cou_code,
    eel_lfs_code,
    eel_hty_code ,
    eel_area_division,
    eel_qal_id ,
    eel_qal_comment,
    eel_comment,
    eel_datelastupdate,
    eel_missvaluequal,
    eel_datasource,
    eel_dta_code) select eel_typ_id,eel_year, sum(eel_value) as eel_value,eel_emu_nameshort,eel_cou_code,eel_lfs_code,eel_hty_code,eel_area_division,2 as eel_qal_id,NULL as eel_qal_comment,
eel_comment, date '2020-07-01' as eel_datelastupdate,eel_missvaluequal,eel_datasource, 'Public' as eel_data_code from wkeelmigration.monthly_landings 
where eel_typ_id=4 and eel_cou_code='FR' and eel_year=2009
group by
eel_typ_id,eel_year, eel_emu_nameshort,eel_cou_code,eel_lfs_code,eel_hty_code,eel_area_division,eel_qal_id,eel_qal_comment,
eel_comment, eel_datelastupdate,eel_missvaluequal,eel_datasource,  eel_data_code ;


select * from datawg.t_eelstock_eel where eel_cou_code='FR' and eel_year=2009 and eel_typ_id=4;
rollback;

However, this will probably be closed in the next datacall, so let's wait
