### ISSUE TITLE
Create a direct interface with postgis with sf and create shp 

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#74]

**Comment by mariazti** [comment]
"load_maps" function in the "maps.R" script was modified in order to read directly the postgis tables (emu, country) of the database. The sf packageallows to encode spatial vector data in a standardized way.

**Comment by mariazti** [comment]
"load_maps" function in the "maps.R" script was modified in order to read directly the postgis tables (emu, country) of the database. The sf packageallows to encode spatial vector data in a standardized way.
[maps.docx](https://github.com/ices-eg/wg_WGEEL/files/2996014/maps.docx)
