### ISSUE TITLE
Series names in Scottland for Silver and Yellow

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#79]

**Comment by cedricbriandgithub** [comment]
Tea : silver eel file Girnoch Burn is misspelled as Girnoch Brun and Shieldaig is misspelled as Shiledag, while this is ok in the recruitment data file.

**Comment by cedricbriandgithub** [comment]
Cédric : the reason for that is that the silver eels and yellow have been extracted from the "old" database which was not corrected so we have to fix that when integrating those series

**Comment by LBeaulaton** [comment]
done
