### ISSUE TITLE
Use a matrix of contrast to predict against 1960-1979

### ISSUE THREAD

**Issue by cedricbriandgithub** [ices-eg/wg_WGEEL#83]

**Comment by elfunesto** [comment]
pour le moment, il y a cette solution qui marche assez bien avoir fait tourner le glm et qui permet d'avoir des intervalles de confiance

`###################################################
### code chunk number 10: model_for_glass_eel_graph_and_predictions
###################################################
# using expand.grid to build a complete grid for predictions
data_ter=expand.grid(year_f=model_ge_area$xlevels$year_f,area=model_ge_area$xlevels$area,
                     site=model_ge_area$xlevels$site[1])
data_ter$year<-as.numeric(as.character(data_ter$year_f))


#predicting
data_ter$p=predict(model_ge_area,newdata=data_ter)
data_ter$se=predict(model_ge_area,newdata=data_ter,se.fit=TRUE)[["se.fit"]]


#in the logscale we removed the arithmetic mean to standardise prediction relatively to
#1960-1980
mean_1960_1979=aggregate(data_ter[data_ter$year<1980,"p"],list(data_ter[data_ter$year<1980,"area"]),mean)
names(mean_1960_1979)=c("area","mean")

data_ter=merge(data_ter,mean_1960_1979,by="area")
data_ter$p_std_1960_1979=exp(data_ter$p-data_ter$mean)
data_ter$p_std_1960_1979_min=exp(data_ter$p-data_ter$mean-1.96*data_ter$se)
data_ter$p_std_1960_1979_max=exp(data_ter$p-data_ter$mean+1.96*data_ter$se)

ggplot(data_ter,aes(x=year,y=p_std_1960_1979))+geom_line(aes(col=area))+geom_ribbon(aes(ymin=p_std_1960_1979_min,ymax=p_std_1960_1979_max,fill=area),alpha=.3)

ggplot(data_ter,aes(x=year,y=p_std_1960_1979))+geom_line(aes(col=area))+geom_ribbon(aes(ymin=p_std_1960_1979_min,ymax=p_std_1960_1979_max,fill=area),alpha=.3)+
  scale_y_log10(name=expression(frac(p,bar(p)[1960-1979])~' log scale'),
                #limits=c(0.005,10),
                breaks=c(0.01,0.1,1,10),
                labels=c("1%","10%","100%","1000%"))

`

**Comment by cedricbriandgithub** [comment]
superb
