### ISSUE TITLE
Norway Yellow

### ISSUE THREAD

**Issue by LBeaulaton** [ices-eg/wg_WGEEL#90]
there is two series for yellow NO (ska and SkaY) ==> check for duplicates

**Comment by cedricbriandgithub** [comment]
I think it's fixed, don't see any problem there.
SELECT * FROM datawg.t_series_ser WHERE ser_cou_code='NO'
239	1000	SkaY	Skagerrak Beach Seine Survey	2
29	1	ImsaGY	Imsa Near Sandnes trapping all	1
196	207	ImsaS	Imsa Silver	3
