### ISSUE TITLE
Bug in shiny visualisation, when only a subset of countries are selected

### ISSUE THREAD

**Issue by LBeaulaton** [ices-eg/wg_WGEEL#96]

**Comment by elfunesto** [comment]
@LBeaulaton  when plotting landings raw+corr, the data where filtered to keep only the subset of selected countries and then prediction was made on this filtered dataset. However, if two many data were missing, the glm was not able to make any predictions. I pushed a fix for this diagram with commit e3a88e1 (make prediction with the whole data set filter the data only after the prediction was made). It makes more sense (avoid that predictions change depending on the selected countries). If it is ok for you and the bug does not affect other diagram, you can close the bug
