### ISSUE TITLE
add descriptions to the shiny

### ISSUE THREAD

**Issue by LBeaulaton** [ices-eg/wg_WGEEL#98]
Currently the buttons refer to things that are not weel described , for instance, landings is for all landings included other landings.... adding tooltips or a description somewhere would help.

**Comment by cedricbriandgithub** [comment]
Also this should include somewhere the units ....

**Comment by elfunesto** [comment]
I added the units as a response to issue #122

**Comment by elfunesto** [comment]
The solution used (table caption) can easily be used to add further details if you provide them to me

**Comment by PhilipJac** [comment]
Added tooltips when hoovering each table button and added information to each table description
