### ISSUE TITLE
Fill in station table with data from data call and t_series_ser table

### ISSUE THREAD

**Issue by LBeaulaton** [ices-eg/wg_WGEEL#99]

**Comment by cedricbriandgithub** [comment]
This still needs to be done for yellow and silver eel series

**Comment by elfunesto** [comment]
why not putting station_map for yellow and silver eel series? Some of them can already be produced

**Comment by cedricbriandgithub** [comment]
Yes, I think this will be done during the data call, we have asked the same questions in Yellow and Silver as in glass eel. But I need to insert missing values in station and those will have been generated by the "left join" query between t_series_ser and station. Once everything is ready we can fill the station table. One of the thing to do is to handle that to someone in ICES, and ask for that data to be integrated and proper id (from ICES) be returned to us.

**Comment by cedricbriandgithub** [comment]
Note : we have the inforamtion and didn't do it !!!! 
The info is in the station tables of dc 2020
